STATUS_COLOR_TEXT=(0,0,0)

STATUS_FREE=0
STATUS_COLOR_FREE=(0,255,0)
STATUS_COLOR_TEXT_FREE=STATUS_COLOR_TEXT

STATUS_BUSSY=1
STATUS_COLOR_BUSSY=(0,0,255)
STATUS_COLOR_TEXT_BUSSY=STATUS_COLOR_TEXT

STATUS_DISABLED=-1
STATUS_COLOR_DISABLED=(150,150,150)
STATUS_COLOR_TEXT_DISABLED=STATUS_COLOR_TEXT

STATUS_SELECTED=2
STATUS_COLOR_SELECTED=(50,20,70)
STATUS_COLOR_TEXT_SELECTED=STATUS_COLOR_TEXT

STATUS_BAD_PARKING=-2
STATUS_COLOR_BAD_PARKING=(222,89,160)
STATUS_COLOR_TEXT_BAD_PARKING=STATUS_COLOR_TEXT